
def get_reward(skiped):
    if skiped == 'skiped':
        reward=1
    elif skiped == 'not skiped':
        reward = 0
    return reward 
    
def get_user_behavior(): #function for memorizing user behavior, he skipped or not
    list=[]
    skiped = 'skiped' #input reaction from user, let's suppose we got user's reacion 
    
    return skiped 
def get_song_features(song):
